# ── Real doctors (Chennai) ────────────────────────────────────────────────────
DOCTORS = [
    {
        "name":"Dr. G. Sengottuvelu","spec":"Interventional Cardiologist",
        "available":True,"slot":"2:00 PM – 5:00 PM",
        "emoji":"👨‍⚕️","color":"#e3f2fd",
        "exp":"25+ years","lang":"English, Tamil, Hindi",
        "hospital":"Apollo Hospitals, 21 Greams Lane, Off Greams Road, Chennai – 600 006",
        "hospital_map":"https://maps.google.com/?q=Apollo+Hospitals+Greams+Road+Chennai",
        "qual":"MBBS, MD, DM, DNB, FRCP (London), FRCP (Glasgow), FSCAI — Fellowship in Interventional Cardiology, France",
        "about":"Dr. G. Sengottuvelu is one of Tamil Nadu's most respected interventional cardiologists with over 25,000 successful procedures. He is Clinical Lead of Structural Heart Interventions at Apollo Hospitals and is internationally recognised for complex coronary and structural heart interventions including TAVI/TAVR. He trained at Madras Medical College and completed advanced fellowship in France.",
    },
    {
        "name":"Dr. Y. Vijayachandra Reddy","spec":"Cardiologist",
        "available":False,"slot":"Fully booked today",
        "emoji":"👨‍⚕️","color":"#fce4ec",
        "exp":"27 years","lang":"English, Telugu, Tamil",
        "hospital":"Apollo Hospitals, 21 Greams Lane, Off Greams Road, Chennai – 600 006",
        "hospital_map":"https://maps.google.com/?q=Apollo+Hospitals+Greams+Road+Chennai",
        "qual":"MD, DM, MRCP (UK), FACC, FCSI — British Commonwealth Scholar, University Hospital of Wales, Cardiff",
        "about":"Dr. Y. Vijayachandra Reddy is an internationally renowned interventional cardiologist, pioneer of transradial interventions and complex high-risk PCI in India. He specialises in cardiac arrhythmias, coronary imaging (FFR, OCT, IVUS), and primary angioplasty for acute myocardial infarction.",
    },
    {
        "name":"Dr. Refai Showkathali","spec":"Interventional Cardiologist",
        "available":True,"slot":"9:00 AM – 12:00 PM",
        "emoji":"👨‍⚕️","color":"#e8f5e9",
        "exp":"18 years","lang":"English, Tamil, Arabic",
        "hospital":"Apollo Hospitals, 21 Greams Lane, Off Greams Road, Chennai – 600 006",
        "hospital_map":"https://maps.google.com/?q=Apollo+Hospitals+Greams+Road+Chennai",
        "qual":"MBBS, MRCP (UK), FRCP — Fellow, Royal College of Physicians; Fellow, American College of Cardiology; Fellow, European Society of Cardiology",
        "about":"Dr. Refai Showkathali is an award-winning interventional cardiologist with expertise in structural heart disease interventions including BAV, TAVI and PFO/ASD closure. He completed a fellowship at King's College Hospital, London and regularly presents research at conferences across Europe and the USA.",
    },
    {
        "name":"Dr. I. Sathyamurthy","spec":"Interventional Cardiologist",
        "available":True,"slot":"10:00 AM – 1:00 PM",
        "emoji":"👨‍⚕️","color":"#fff8e1",
        "exp":"37+ years","lang":"English, Tamil, Telugu",
        "hospital":"Apollo Hospitals, 21 Greams Lane, Off Greams Road, Chennai – 600 006",
        "hospital_map":"https://maps.google.com/?q=Apollo+Hospitals+Greams+Road+Chennai",
        "qual":"MBBS, MD, DM — FACC (USA), FRCP Edinburgh, FRCP Glasgow, DSc (Honoris Causa) Dr. MGR Medical University",
        "about":"Dr. Immaneni Sathyamurthy is one of India's most decorated cardiologists, recipient of the Padma Shri, Dr. B.C. Roy National Award, and TANSA Award for Medical Sciences. With 37+ years of experience and 230+ publications, he is a member of the Tamil Nadu Medical Council and a globally respected leader in interventional cardiology.",
    },
    {
        "name":"Dr. Robert Mao","spec":"Cardiac & Vascular Surgeon",
        "available":False,"slot":"Fully booked today",
        "emoji":"👨‍⚕️","color":"#f3e5f5",
        "exp":"38+ years","lang":"English, Tamil",
        "hospital":"Apollo Hospitals, 21 Greams Lane, Off Greams Road, Chennai – 600 006",
        "hospital_map":"https://maps.google.com/?q=Apollo+Hospitals+Greams+Road+Chennai",
        "qual":"MBBS (1977), MD General Medicine (1980), DM Cardiology (1982) — Karnataka Medical University",
        "about":"Dr. Robert Mao is a highly respected cardiac and vascular surgeon with over 38 years of experience. He specialises in open heart surgery, aortic aneurysm surgery, PCI, vascular surgery, and mitral/heart valve replacement. He has published extensively in reputed medical journals.",
    },
    {
        "name":"Dr. A. Muruganathan","spec":"Physician & Diabetologist",
        "available":True,"slot":"Available now",
        "emoji":"👨‍⚕️","color":"#e0f7fa",
        "exp":"32+ years","lang":"English, Tamil, Hindi",
        "hospital":"AG Hospital, Tirupur (Telemedicine consults available, Chennai)",
        "hospital_map":"https://maps.google.com/?q=AG+Hospital+Tirupur",
        "qual":"MBBS, MD — Former Member, Medical Council of India (2007–2012); Member, Nursing Council of India (2008–2012)",
        "about":"Dr. A. Muruganathan is a nationally renowned physician with 32+ years of experience in cardiology and diabetology. He is the managing trustee of the Tirupur Social Service Organisation and has organised several national and international medical conferences including Commonwealth Medical Association workshops.",
    },
]
